### PR TITLE
switch ci to gh action & extend [compat] CategoricalArrays="...,0.9"

### PR DESCRIPTION
**Pull request by ablaom**
#72

### CODE REVIEW

**Comment by DilumAluthge** [comment]
YAML parse error

**Comment by DilumAluthge** [comment]
If you copy the `ci.yml` file into an online YAML parser, you should be able to figure out where the parse error is

**Comment by ablaom** [comment]
I'm now getting a package conflict error which I am unable to reproduce locally. Mmmm.

**Comment by ablaom** [comment]
Okay i can reproduce in julia 1.3

**Comment by ablaom** [comment]
Actually, silently failing in 1.5

**Comment by ablaom** [comment]
Okay the test only fail is due to a compatibility conflict and the following is at least one obstacle:

https://github.com/JuliaStats/Distributions.jl/pull/1230

**Comment by ablaom** [comment]
This conflict needs https://github.com/JuliaStats/Distributions.jl/pull/1230

**Comment by ablaom** [comment]
CI still not seeing Distributions 0.24.5

**Pull request merged**
