### PR TITLE
bump up compat bound for flux

### PR DESCRIPTION
**Pull request by tlienart**
would be good to have a release with this please (assuming it passes tests)

### CODE REVIEW

**Comment by ablaom** [comment]
Okay, the fail shows there has been some real change in behaviour of Flux which needs to be investigated. 

@ayush-1506 Be great if you can look into this. It may not be relevant, but in case it is and you did not know, the global RNG behaves differently in julia 1.4+ (and unfortunately Flux does not expose the RNG used in intialization).

**Comment by ablaom** [comment]
@tlienart In case this is not resolved quickly, you may want to find some workaround?

**Comment by ayush-1506** [comment]
Looking at the travis log, it looks like the model isn't converging as fast as it previously was (Even after the same number of epochs, loss doesn't decrease as much as it should). I'll dig into what might be causing this.

**Comment by ablaom** [comment]
https://github.com/FluxML/model-zoo/issues/244

**Comment by ablaom** [comment]
@ayush-1506 It seems to me that Flux behaviour in a simple case has changed in some way between versions. This is pretty serious.  It would be good to get a MWE and post an issue at Flux so that this can get some attention.  

I don't think the issue at model zoo you raised has been noticed. The issue is not just poorer performance but that behaviour has fundamentally changed, which might suggest a bug. (I think the RNG business I raised is a red herring; if we stick to the same julia version, this is not an issue.)

Be great if you have some time to look into this. 🙏

**Comment by ablaom** [comment]
Closing in favour of #74

**Pull request closed without merging**
